repos:
  - repo: local
    hooks:
      - id: cleanup-script
        name: Run cleanup script
        entry: uv run ./.pre-commit-scripts/run-cleanup.py
        language: system
        pass_filenames: true
        stages: [pre-commit]
