repos:
  - repo: local
    hooks:
      - id: cleanup-script
        name: Run cleanup script
        entry: ./scripts/cleanup.sh
        language: script
        pass_filenames: true
        stages: [pre-commit]
