# global config
mixed-port: 7890
allow-lan: true
mode: rule
global-client-fingerprint: chrome # 设置全局客户端指纹为 Chrome，使 Clash 在建立连接时模拟 Chrome 浏览器的 TLS 指纹，增强隐私性和绕过某些网站的指纹检测
# geo config
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 48 # 更新间隔，单位：小时
geox-url:
  geoip: "https://cdn.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://cdn.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://cdn.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://cdn.gh-proxy.org/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"
log-level: info
ipv6: true
external-controller: 0.0.0.0:9090
secret: <secret>
unified-delay: true
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true
# dns config
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private"
    - "rule-set:direct"
    - "geosite:connectivity-check"
    - "geosite:private"
    - "rule-set:fake-ip-filter"
  prefer-h3: false # 如果DNS服务器支持DoH3会优先使用h3，提升性能
  respect-rules: true # 让 DNS 解析遵循 Clash 的路由规则，不要和prefer-h3配合使用
  default-nameserver: # 解析DNS服务器的域名，所以这里必须为ip
    - tls://223.5.5.5:853
    - tls://1.12.12.12:853
  # nameserver:
  #   - https://cloudflare-dns.com/dns-query
  #   - https://dns.google/dns-query
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver: # 代理节点域名解析服务器
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  fallback:
    - tls://8.8.4.4:853
    - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  #当前有BUG，直连的域名，解析后有时候不会覆盖第一阶段(此时还没有进入规则匹配)解析的IP
  #direct-nameserver: # 规则匹配到直连时使用的DNS，既然是可以直连的，当然要用国内DNS
  #  - https://dns.alidns.com/dns-query
  #  - https://doh.pub/dns-query
  nameserver-policy:
    "geosite:cn,private":
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
    "geosite:gfw,geolocation-!cn":
      - https://cloudflare-dns.com/dns-query
      - https://dns.google/dns-query

# tun config
tun:
  enable: true
  # stack: mixed # system/gvisor/mixed
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true # 避免冗余路由污染系统表
  dns-hijack:
    - any:53
    - tcp://any:53
  mtu: 1500 # 减少 MTU 问题，如网页无法打开、测速慢
  gso: false # 启用通用分段卸载（提升性能）(enable this option causes the network disconnect, tested on the debain12 virtual machine )
  gso-max-size: 65536
  udp-timeout: 300 # UDP 会话保持时间
  exclude-interface:
    - "docker0"
    - "br-331d4f0912d3"
    - "br-03bb4e621fce"
# 流量嗅探，对于redir-host情况（真实ip),嗅探域名
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  # 嗅探结果跳过
  skip-domain:
    - "+.baidu.com"
    - "+.bilibili.com"
profile:
  store-selected: true
  store-fake-ip: true
proxy-providers:
  <subscription name>:
    type: http
    url: <subscription url>
    path: ./proxy_providers/<subscription name>.yaml
    interval: 3600
    proxy: DIRECT
    size-limit: 0
    header:
      User-Agent:
        - "Clash/v1.18.0"
        - "mihomo/1.18.3"
    health-check:
      enable: true
      url: "https://cp.cloudflare.com/generate_204"
      interval: 86400
      timeout: 10000
      lazy: true
      expected-status: 204
proxy-group-anchor:
  url-test: &url-test
    type: url-test
    include-all: true
    hidden: true
    url: "https://cp.cloudflare.com/generate_204"
    interval: 180
    lazy: true
    tolerance: 50
    timeout: 10000
    disable-udp: false
    max-failed-times: 3
  fallback: &fallback
    type: fallback
    url: "https://cp.cloudflare.com/generate_204"
    interval: 180
    lazy: true
    timeout: 10000
    disable-udp: false
    max-failed-times: 3
  std-groups: &std-groups
    # - 🇭🇰️ 香港
    # - 🇭🇰️ 香港➰
    # - 🇹🇼 台湾
    # - 🇹🇼 台湾➰
    # - 🇯🇵 日本
    # - 🇯🇵 日本➰
    # - 🇸🇬 新加坡
    # - 🇸🇬 新加坡➰
    # - 🇺🇸 美国
    # - 🇺🇸 美国✔️
    # - 🇺🇸 美国➰
    # - 🇬🇧 英国
    # - 🇬🇧 英国➰
    - 自建
    # - 🧭 Break
  loose-groups: &loose-groups
    # - 🇭🇰️ 香港
    # - 🇭🇰️ 香港➰
    # - 🇹🇼 台湾
    # - 🇹🇼 台湾➰
    # - 🇯🇵 日本
    # - 🇯🇵 日本➰
    # - 🇸🇬 新加坡
    # - 🇸🇬 新加坡➰
    # - 🇺🇸 美国
    # - 🇺🇸 美国✔️
    # - 🇺🇸 美国➰
    # - 🇬🇧 英国
    # - 🇬🇧 英国➰
    - 自建
    # - 🧭 Break
    - DIRECT
  ai-groups: &ai-groups # - 🇺🇸 美国✔️
    - 自建
    # - 🇺🇸 美国
proxy-groups:
  - name: 🧭 Break
    <<: *url-test
    filter: (?i)^master
  - name: 🇭🇰️ 香港
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(港|Hong\sKong).*$
  - name: 🇭🇰️ 香港➰
    <<: *url-test
    filter: (?i)^master.*(港|Hong\sKong)[^|]*$
  - name: 🇹🇼 台湾
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(台|Taiwan).*$
  - name: 🇹🇼 台湾➰
    <<: *url-test
    filter: (?i)^master.*(台|Taiwan)[^|]*$
  - name: 🇯🇵 日本
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(日|Japan).*$
  - name: 🇯🇵 日本➰
    <<: *url-test
    filter: (?i)^master.*(日|Japan)[^|]*$
  - name: 🇸🇬 新加坡
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(新|Singapore).*$
  - name: 🇸🇬 新加坡➰
    <<: *url-test
    filter: (?i)^master.*(新|Singapore).*$
  - name: 🇺🇸 美国
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(美|USA).*$
  - name: 🇺🇸 美国✔️
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(美|USA).*(原生).*$
  - name: 🇺🇸 美国➰
    <<: *url-test
    filter: (?i)^master.*(美|USA)[^|]*$
  - name: 🇬🇧 英国
    <<: *url-test
    filter: (?i)^master(?!.*中转).*(英|UK).*$
  - name: 🇬🇧 英国➰
    <<: *url-test
    filter: (?i)^master.*(英|UK)[^|]*$
  - name: Microsoft
    type: select
    icon: https://www.clashverge.dev/assets/icons/microsoft.svg
    proxies: *loose-groups
  - name: Steam
    type: select
    icon: https://www.clashverge.dev/assets/icons/steam.svg
    proxies: *std-groups
  - name: Video
    type: select
    icon: https://www.clashverge.dev/assets/icons/netflix.svg
    proxies: *loose-groups
  - name: Github
    <<: *fallback
    icon: https://www.clashverge.dev/assets/icons/github.svg
    proxies: *std-groups
  - name: Google
    <<: *fallback
    icon: https://www.clashverge.dev/assets/icons/google.svg
    proxies: *std-groups
    lazy: true
  - name: Spotify
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png
    proxies: *std-groups
  - name: Twitter
    type: select
    icon: https://www.clashverge.dev/assets/icons/twitter.svg
    proxies: *std-groups
  - name: Claude
    <<: *fallback
    icon: https://www.clashverge.dev/assets/icons/claude.svg
    proxies: *ai-groups
  - name: Chatgpt
    <<: *fallback
    icon: https://www.clashverge.dev/assets/icons/chatgpt.svg
    proxies: *ai-groups
  - name: 广告拦截
    type: select
    icon: https://www.clashverge.dev/assets/icons/block.svg
    proxies:
      - REJECT
      - DIRECT
      - PROXY
  - name: 代理模式
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    proxies:
      - PROXY
      - DIRECT
  - name: 自建
    type: select
    icon: https://www.clashverge.dev/assets/icons/link.svg
    include-all: true
    filter: hotfree
  - name: Master
    type: select
    icon: https://www.clashverge.dev/assets/icons/speed.svg
    proxies: *std-groups
    include-all: true
    filter: (?i)^master
  - name: PROXY
    type: select
    icon: https://www.clashverge.dev/assets/icons/adjust.svg
    proxies:
      - Master
      - 自建
      - DIRECT
rule-anchor:
  domian: &domian
    type: http
    behavior: domain
    interval: 86400
  classical: &classical
    type: http
    behavior: classical
    interval: 86400
  ip: &ip
    type: http
    behavior: ipcidr
    interval: 86400
rule-providers:
  fake-ip-filter:
    <<: *domian
    format: text
    url: https://cdn.jsdelivr.net/gh/juewuy/ShellCrash@dev/public/fake_ip_filter.list
    path: ./ruleset/fake_ip_filter.list
  steam:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Steam/Steam.yaml
    path: ./ruleset/steam.yaml
  spotify:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml
    path: ./ruleset/spotify.yaml
  twitter:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.yaml
    path: ./ruleset/twitter.yaml
  github:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml
    path: ./ruleset/github.yaml
  microsoft:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml
    path: ./ruleset/microsoft.yaml
  openai:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OpenAI/OpenAI.yaml
    path: ./ruleset/openai.yaml
  claude:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.yaml
    path: ./ruleset/claude.yaml
  reject:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: ./ruleset/reject.yaml
  icloud:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: ./ruleset/icloud.yaml
  apple:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: ./ruleset/apple.yaml
  gemini:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Gemini/Gemini.yaml
    path: ./ruleset/gemini.yaml
  google:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml
    path: ./ruleset/google.yaml
  proxy:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: ./ruleset/proxy.yaml
  direct:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: ./ruleset/direct.yaml
  private:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: ./ruleset/private.yaml
  gfw:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: ./ruleset/gfw.yaml
  greatfire:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt
    path: ./ruleset/greatfire.yaml
  tld-not-cn:
    <<: *domian
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: ./ruleset/tld-not-cn.yaml
  telegramcidr:
    <<: *ip
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: ./ruleset/telegramcidr.yaml
  cncidr:
    <<: *ip
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: ./ruleset/cncidr.yaml
  lancidr:
    <<: *ip
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: ./ruleset/lancidr.yaml
  applications:
    <<: *classical
    url: https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: ./ruleset/applications.yaml
rules:
  - DOMAIN-SUFFIX,olevod.com,Video
  - DOMAIN-SUFFIX,olelive.com,Video
  - DOMAIN-SUFFIX,olemovienews.com,Video
  - DOMAIN-SUFFIX,iyf.tv,Video
  - DOMAIN-SUFFIX,anygate.vip,Video
  - DOMAIN-SUFFIX,generalcdn.com,Video
  - DOMAIN-SUFFIX,newwycdn.com,Video
  - DOMAIN-SUFFIX,newyvpa.com,Video
  - DOMAIN-SUFFIX,tfbgddd.com,Video
  - DOMAIN-SUFFIX,tfbgeee.com,Video
  - DOMAIN-SUFFIX,wyav.tv,Video
  # - DOMAIN-SUFFIX,debian.org, 🇹🇼 台湾
  # - DOMAIN-SUFFIX,apache.org, 🇹🇼 台湾
  - DOMAIN-SUFFIX,inoecho.xyz,DIRECT
  - RULE-SET,applications,DIRECT
  - RULE-SET,steam,Steam
  - DOMAIN-SUFFIX,deepseek.com,DIRECT
  - DOMAIN-SUFFIX,deepseek.com.cn,DIRECT
  - DOMAIN-SUFFIX,diagrams.org,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,reject,广告拦截
  - RULE-SET,private,DIRECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,gemini,Claude
  - RULE-SET,google,Google
  - RULE-SET,github,Github
  - RULE-SET,spotify,Spotify
  - RULE-SET,twitter,Twitter
  - RULE-SET,openai,Chatgpt
  - DOMAIN-SUFFIX,claudeusercontent.com,Claude
  - DOMAIN-SUFFIX,openrouter.ai,Claude
  - RULE-SET,claude,Claude
  - RULE-SET,microsoft,Microsoft
  - RULE-SET,telegramcidr,PROXY
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT
  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,代理模式
